export interface PartnerTestQuestion {
  id: string;
  label: string;
  answer: string | string[];
  type: "single" | "multi";
  options: string[];
}

export const SURVEY_DATA: PartnerTestQuestion[] = [
  {
    id: "feeling_after_time_together",
    label: "How do you usually feel after spending time with your partner?",
    answer: "",
    type: "single",
    options: [
      "Energized and happy",
      "Calm and content",
      "Neutral / no strong feeling",
      "Drained or exhausted",
      "Confused about my feelings",
    ],
  },
  {
    id: "conflict_communication",
    label: "How well do you communicate during conflicts?",
    answer: "",
    type: "single",
    options: [
      "Very openly and respectfully",
      "Mostly well, with minor issues",
      "Sometimes it works, sometimes not",
      "Poorly, often misunderstood",
      "We avoid conflict entirely",
    ],
  },
  {
    id: "emotional_safety",
    label: "Do you feel emotionally safe with your partner?",
    answer: "",
    type: "single",
    options: [
      "Completely safe",
      "Mostly safe",
      "Sometimes unsure",
      "Rarely safe",
      "Not safe at all",
    ],
  },
  {
    id: "life_goals_alignment",
    label: "How aligned are your long-term life goals?",
    answer: "",
    type: "single",
    options: [
      "Almost identical",
      "Mostly aligned",
      "Some overlap",
      "Very different",
      "I don't know their goals",
    ],
  },
  {
    id: "feeling_understood",
    label: "How often do you feel understood by your partner?",
    answer: "",
    type: "single",
    options: ["Always", "Often", "Sometimes", "Rarely", "Never"],
  },
  {
    id: "trust",
    label: "Do you trust your partner completely?",
    answer: "",
    type: "single",
    options: ["Yes, fully", "Mostly", "Some doubts", "Rarely", "Not at all"],
  },
  {
    id: "handling_vulnerabilities",
    label: "How do they handle your vulnerabilities?",
    answer: "",
    type: "single",
    options: [
      "With care and support",
      "Usually supportive",
      "Neutral",
      "Sometimes dismissive",
      "Often dismissive or hurtful",
    ],
  },
  {
    id: "personal_growth_support",
    label: "Do you feel supported in your personal growth?",
    answer: "",
    type: "single",
    options: [
      "Strongly supported",
      "Mostly supported",
      "Somewhat supported",
      "Not really",
      "Actively discouraged",
    ],
  },
  {
    id: "relationship_doubts",
    label: "How often do you have doubts about the relationship?",
    answer: "",
    type: "single",
    options: ["Never", "Rarely", "Sometimes", "Often", "Almost always"],
  },
  {
    id: "disagreement_resolution",
    label: "How do you resolve disagreements?",
    answer: [],
    type: "multi",
    options: [
      "Talk things through calmly",
      "Take time apart and revisit",
      "Compromise",
      "One person gives in",
      "Arguments escalate",
      "Issues remain unresolved",
    ],
  },
  {
    id: "shared_values",
    label: "Do you share similar values?",
    answer: [],
    type: "multi",
    options: [
      "Family values",
      "Financial mindset",
      "Lifestyle preferences",
      "Career ambitions",
      "Moral/ethical beliefs",
      "We differ on most",
    ],
  },
  {
    id: "future_together",
    label: "How do you feel about your future together?",
    answer: "",
    type: "single",
    options: [
      "Very excited and confident",
      "Optimistic",
      "Unsure",
      "Doubtful",
      "I don't see a future",
    ],
  },
  {
    id: "authenticity",
    label: "Do you feel like yourself around them?",
    answer: "",
    type: "single",
    options: [
      "Completely myself",
      "Mostly myself",
      "Sometimes I hold back",
      "Often not myself",
      "I feel like a different person",
    ],
  },
  {
    id: "public_treatment",
    label: "How do they treat you in front of others?",
    answer: "",
    type: "single",
    options: [
      "Very respectful and loving",
      "Mostly respectful",
      "Neutral",
      "Sometimes disrespectful",
      "Often disrespectful",
    ],
  },
  {
    id: "boundary_respect",
    label: "Do they respect your boundaries?",
    answer: "",
    type: "single",
    options: ["Always", "Mostly", "Sometimes", "Rarely", "Never"],
  },
  {
    id: "reaction_when_upset",
    label: "How do they react when you're upset?",
    answer: "",
    type: "single",
    options: [
      "Supportive and caring",
      "Tries to help",
      "Unsure what to do",
      "Dismissive",
      "Makes it worse",
    ],
  },
  {
    id: "attraction",
    label: "Are you physically and emotionally attracted to them?",
    answer: "",
    type: "single",
    options: [
      "Strongly both",
      "Mostly both",
      "Only one of the two",
      "Weak attraction",
      "No attraction",
    ],
  },
  {
    id: "quality_time",
    label: "Do you enjoy spending time together without distractions?",
    answer: "",
    type: "single",
    options: ["Always", "Often", "Sometimes", "Rarely", "Never"],
  },
  {
    id: "relationship_effort",
    label: "How much effort do both of you put into the relationship?",
    answer: "",
    type: "single",
    options: [
      "Equal and high effort",
      "Mostly balanced",
      "Slight imbalance",
      "One-sided effort",
      "Very little effort overall",
    ],
  },
  {
    id: "feeling_appreciated",
    label: "Do you feel appreciated?",
    answer: "",
    type: "single",
    options: ["Always", "Often", "Sometimes", "Rarely", "Never"],
  },
  {
    id: "choose_again",
    label: "Would you choose them again if you met today?",
    answer: "",
    type: "single",
    options: [
      "Definitely yes",
      "Probably yes",
      "Not sure",
      "Probably not",
      "Definitely not",
    ],
  },
  {
    id: "social_circle_perception",
    label: "How do your friends/family view the relationship?",
    answer: "",
    type: "single",
    options: [
      "Very positive",
      "Mostly positive",
      "Mixed opinions",
      "Mostly negative",
      "Very negative",
    ],
  },
  {
    id: "energy_balance",
    label: "Do you feel more energized or drained by the relationship?",
    answer: "",
    type: "single",
    options: [
      "Strongly energized",
      "Slightly energized",
      "Neutral",
      "Slightly drained",
      "Strongly drained",
    ],
  },
  {
    id: "long_term_vision",
    label: "Can you imagine growing old with them?",
    answer: "",
    type: "single",
    options: ["Absolutely", "Likely", "Unsure", "Unlikely", "Not at all"],
  },
];